@startuml
start
:Message from RabbitMQ Queue;
if (Parse into LogMessage?) then (yes)
  :Process Message;
  if (Success?) then (yes)
    :Log Success;
  else (no)
    :Log Exception;
  endif
else (no)
  :Log Parsing Error;
endif
stop
@enduml
